server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: v4n3ss4

  jpa:
    hibernate:
      ddl-auto: update

logging:
   level:
     org:
       springframework:
         security: TRACE

